#!/usr/bin/env python
# coding=utf-8
#
# cftest - CLI tool for testing solutions to problems from http://www.codeforces.com
# Copyright (C) 2014-2015  Zoran Plesivčak <zplesiv@gmail.com>
# This software is distributed under the terms of the MIT License.
#

import sys
import argparse
import re
import os

# Python2 and Python3 compatibility
try:
    from urllib2 import urlopen
    from HTMLParser import HTMLParser
except:
    from urllib.request import urlopen
    from html.parser import HTMLParser

# Default configuration
DEFAULT_LANGUAGES = ["cpp"]
CONTEST_DIR_PREFIX = ""


# -----------------------------------------------------------------------------

# Construct parser
parser = argparse.ArgumentParser(
    description=
        """Select contest (number) and optionally problems (letters) for which
        to prepare testing environment in current directory.
        """,
    epilog="Examples..."
)
parser.add_argument("CONTEST", help="Codeforces contest number")
parser.add_argument("PROBLEMS", action="append", type=str, nargs="*",
    help="Problems' letters (Defaults to all problems)")
parser.add_argument(
    "-f", "--force", action="store_true",
    help="Overwrite existing directories (Not enabled by default)"
)
parser.add_argument(
    "-d", "--create-subdirs", type=int, choices=[0, 1, 2], default=1,
    help=
        """Levels of directories to create (Defaults to 1, e.g. create
        directories for problems)"""
)
parser.add_argument(
    "-l", "--lang", action="append", choices=["py", "cpp"], default=[],
    help="Languages for which test environment will be prepared (Default is " +
        str(DEFAULT_LANGUAGES) + ")"
)

# -----------------------------------------------------------------------------

# Contest parser class
class CodeforcesContestParser(HTMLParser):

    def __init__(self, contest):
        HTMLParser.__init__(self)
        self.contest = contest
        self.start_contest = False
        self.start_problem = False
        self.name = ''
        self.problems = []
        self.problem_names = []

    def handle_starttag(self, tag, attrs):
        if self.name == '' and attrs == [('style', 'color: black'), ('href', '/contest/%s' % (self.contest))]:
                self.start_contest = True
        elif tag == 'option':
            if len(attrs) == 1:
                regexp = re.compile(r"'[A-Z]'")
                string = str(attrs[0])
                search = regexp.search(string)
                if search is not None:
                    self.problems.append(search.group(0).split("'")[-2])
                    self.start_problem = True

    def handle_endtag(self, tag):
        if tag == 'a' and self.start_contest:
            self.start_contest = False
        elif self.start_problem:
            self.start_problem = False

    def handle_data(self, data):
        if self.start_contest:
            self.name = data
        elif self.start_problem:
            self.problem_names.append(data)

# Parses the contest page
def parse_contest(contest):
    url = 'http://codeforces.com/contest/{0}'.format(contest)
    html = urlopen(url).read()
    parser = CodeforcesContestParser(contest)
    parser.feed(html.decode('utf-8'))
    return parser

# Create directory-structure or notify if exist already
def create_directories(path):
    try:
        os.makedirs(path)
    except:
        print('WARNING: Directory "{0}" already exists{1}!'.format(
            os.path.relpath(path),
            " and it's NOT EMPTY" if os.listdir(path) else ""))

# -----------------------------------------------------------------------------

if __name__ == "__main__":
    # When no arguments given show Help
    if len(sys.argv) == 1:
        parser.print_help()
        sys.exit(1)

    # Parse and normalize CLI arguments
    args = parser.parse_args()
    args.lang = sorted(set(args.lang)) if args.lang else DEFAULT_LANGUAGES
    args.PROBLEMS = sorted(set(''.join(args.PROBLEMS[0])))

    # Parse Codeforces.com for contest and problems
    content = parse_contest(args.CONTEST)

    # All problems if none explicitly chosen
    if len(args.PROBLEMS) == 0:
        problems = content.problems
    else:
        problems = sorted(set(content.problems) & set(args.PROBLEMS))

    if len(problems) == 0:
        sys.stderr.write("No eligible problems chosen...\n")
        sys.stderr.write("Problems available in contest {0}: {1}.\n".
            format(args.CONTEST, str(content.problems or "[<no problems>]")))
        sys.exit(2)

    # Create contest directory starting from current directory (if needed)
    contest_path = os.curdir
    if (args.create_subdirs == 2):
        contest_path = os.path.join(contest_path,
            CONTEST_DIR_PREFIX + str(args.CONTEST))
        create_directories(contest_path)

    for idx, prb in enumerate(problems):
        problem_path = os.path.join(contest_path, prb)
        create_directories(problem_path)
        #try:
            #os.makedirs(problem_path)
        #except:
            #print('WARNING: Directory "{0}" already exists!'.
                #format(os.path.normpath(contest_path)))



        #folder = '%s/%s/' % (contest, problem)
        #call(['mkdir', '-p', folder])
        #call(['cp', '-n', TEMPLATE, '%s/%s/%s.cc' % (contest, problem, problem)])
        #num_tests = parse_problem(folder, contest, problem)
        #print('%d sample test(s) found.' % num_tests)
        #generate_test_script(folder, num_tests, problem)
        #print ('========================================')

    #print(args.create_subdirs)
    print(args.force)
    #print(args.lang)
    #print(args.CONTEST)
    #print(args.PROBLEMS)
    #print(content.contest)
    #print(content.start_contest)
    #print(content.start_problem)
    #print(content.name)
    #print(content.problems)
    #print(content.problem_names)
